server:
  port: 8011

spring:
  application:
    name: service1

eureka:
  instance:
    prefer-ip-address: true  #유레카 서버에 애플리케이션 이름에 매핑되는 호스트명이 기본적으로 동록되게 (호스트명이 아닌 ip주소를 대신 등록하겠다는 것)
  client:
    register-with-eureka: true  #유레카 서비스에 자신을 등록 여부
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"